# Changing this file necessitates a server restart
name: "Evidence Living Preprints"
abbreviation: "Evidence"
issn: ""
tagline: "a <strong>next-generation</strong> preprint server for all sciences, going above, beyond, and forward from PDFs."
logo_url: "https://github.com/evidencepub/brand/blob/main/logo/png/original_600x600.png?raw=true"
url: "https://evidencepub.io"
editor_email: "conp.dev@gmail.com"
noreply_email: "conp.dev@gmail.com"
launch_date: "2025-03-25"
bluesky: ""
mastodon_url: ""
google_analytics: ""
github: "evidencepub/evidence"
reviews: "evidencepub/technical-screening"
papers_repo: "evidencepub/preprints"
papers_html_url: "https://evidencepub.github.io/preprints"
reviewers_url: ""
reviewers_signup_url: ""
reviewers_lookup_url: ""
product: "software" # the *thing* being submitted for review
submission_enquiry: |-
  **Project repository URL:** INSERT YOUR REPOSITORY LINK HERE

  Briefly describe your software, its research application and any questions you have about the JOSS submission criteria.
paper_types: []
bot_username: editorialbot
features:
  tracks: true
